### ISSUE TITLE
Unable to use this library with proguard enabled

### ISSUE THREAD

**Issue by saeedjassani** [noties/Markwon#1]
I'm getting the following error when I use this library with proguard enabled:

`Warning:ru.noties.markwon.spans.AsyncDrawableSpan: can't find referenced class ru.noties.markwon.spans.AsyncDrawableSpan$Alignment`
`Warning:there were 2 unresolved references to classes or interfaces.`
`Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.`
`Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.`
`> Job failed, see logs for details`

I tried adding this line in proguard-rules.pro but it didn't helped either:

`-keep class ru.noties.markwon.** { *; }`

PS: If I disable proguard, it works fine.

**Comment by noties** [comment]
@saeedjassani Hey! Thanks for the report. `Alignment` inside `AsyncDrawableSpan` is actually an `@IntDef`, it should not affect compilation at all, so it's safe to suppress. The bug here is this: `Alignment` is missing `@Retention` annotation. The workaround for now - add this to your ProGuard rules:

```
-dontwarn ru.noties.markwon.spans.AsyncDrawableSpan$Alignment
```

**Comment by saeedjassani** [comment]
Thanks for your reply, its working now

**Comment by noties** [comment]
I will keep it open, so it is fixed for the next release
