### ISSUE TITLE
Markdown format image scaled

### ISSUE THREAD

**Issue by yjouyang** [noties/Markwon#114]
* **Markwon version**: _3.0.1-SNAPSHOT_

1. I want to display an image with something like "\!\[](https:xxx.png)"
2. `AsyncDrawable` doesn't supply a way to change `imageSize` but the actual size of the image is loaded async
3. The default implementation of `ImageSizeResolver` scale the image to fit the canvas width. **But** canvas width is quit small because the placeholder (OBJ image) initializes the width of canvas so when the image is loaded, it's scaled

So how could I display an image with more reasonable size? Is implementing a custom `ImageSizeResolver` the right way?

**Comment by noties** [comment]
Hello @yjouyang !

_Native_ markdown does not support specifying sizes for images (based on commonmark specification). But _native_ markdown supports HTML. So, if you are using HtmlPlugin, all you have to do is change `![](https:xxx.png)` -> `<img src="https:xxx.png" width="30%" >`. `<img>` tag actually allows specifying image size in multiple ways:
* `width=100px` - image will be 100px in width, height will be calculated based on this value and scaled down/up to keep the ratio
* `width=100%` - the same as above, but image will take full width of a canvas (height will be determined automatically)
* `width=100px height=100px` will make image this exact size
* `width=100% height=100%` is **not** possible, as height in percents is not supported

Also,
> The default implementation of ImageSizeResolver scale the image to fit the canvas width. But canvas width is quit small because the placeholder (OBJ image) initializes the width of canvas so when the image is loaded, it's scaled

can be true only if you have TextView.width=wrap_content (which I doubt). And... in this case image won't change TextView.width because it doesn't work this way. The only customization that default ImageSizeResolver is doing is - _scale image **down**_ if it's width exceeds canvas width. Otherwise it will be kept untouched (unmodified). 

You can also write own implementation of `ImageSizeResolver` to fit your needs. And there you can go crazy 😄

**Comment by yjouyang** [comment]
@noties Thank you for your reply!

And yep, I have TextView.width=wrap_content and it must be wrap_content, which kind of drives me mad right now. 

However, I find a way to make the image scaled properly. Although the textview is wrap_content, but I can calculate its max width, which should be considered when displaying the image. So I call `AsyncDrawable.initWithKnownDimensions` with the max width, and reset the drawable result which will recalculate the bounds of the drawable.

It seems to work nicely, but I think it's a little tricky. Do you have any better idea?

**Comment by noties** [comment]
Hello @yjouyang !

Well, if it works for your specific needs, I would say that it is fine 😄 . Just out of curiosity, can you show how you are doing it? In case someone will also have this problem

**Comment by yjouyang** [comment]
@noties Although I've make it work, I'm still wondering if there is an "official" way to support TextView with wrap_content? 

Code:
```Kotlin
data class Dimension(val canvasWidth: Int, val textSize: Float)

private class DrawableLoader(private val context: Context, private val dimension: Dimension? = null): AsyncDrawableLoader() {


    .....

    override fun cancel(destination: String) {
        requestTracker.remove(destination)?.get()?.cancel()
    }

    override fun load(destination: String, drawable: AsyncDrawable) {
        val assetDrawable = LocalSticker.fromUrl(destination)?.run { AssetsReader.createDrawable(context, this.assetPath()) }
        if (assetDrawable != null) {
            drawable.setResult2(assetDrawable)
            return
        }
        ImageLoader.with(context)
                .load(destination).also {
                    requestTracker[destination] = WeakReference(it)
                }
                .fetch(object : ImageLoader.LoadListener<String, Drawable> {
                    override fun onResourceReady(model: String?, resource: Drawable?) {
                        requestTracker.remove(destination)
                        drawable.setResult2(resource!!)
                    }

                    override fun onException(exception: Exception?, model: String?) {
                        requestTracker.remove(destination)
                        drawable.setResult2(ContextCompat.getDrawable(context, R.drawable.bg_image_load_failed)!!)
                    }
                })
    }

    fun AsyncDrawable.setResult2(drawable: Drawable) {
        dimension?.let {
            initWithKnownDimensions(it.canvasWidth, it.textSize)
        }
        drawable.apply {
            setBounds(0, 0, intrinsicWidth, intrinsicHeight)
        }.let {
            this.result = it
            this.bounds = it.bounds
        }
    }
}
```
`canvasWidth` in `Dimension` is the max display width of TextView, so image will show fitting it's original size instead of being scaled

**Comment by noties** [comment]
Hello @yjouyang !

Thanks for sharing your code. Now we can officially state to use your solution as the official way to deal with images in a TextView with `width=wrap_content` 😉 🙌 !
