### ISSUE TITLE
NullPointerException at HtmlEntities.readEntities 

### ISSUE THREAD

**Issue by biodunalfet** [noties/Markwon#121]
* **Markwon version**:  3.0.0

The markdown on displays successfully on some devices while it crashes on others. We have been able to trace the bug to this line

```
Caused by java.lang.NullPointerException
org.commonmark.internal.util.Html5Entities.readEntities (Html5Entities.java:48)
```

I also noticed it is not OS specific. It crashes on some devices that run on OS ranging from Android 9, 8, 7, 6 and Q. Some of the devices include Galaxy J7 Prime, Galaxy A6+, Infinix Hot S3,  Galaxy Note9,  Galaxy S7 edge. 

[Here's](https://gist.githubusercontent.com/biodunalfet/9544e5b2a9d97bd40c87985915dc19b7/raw/de8c34f6565378d1b61f796fb30041345eb4b12a/barter_t_and_c.md) the markdown file I'm trying to render

**Comment by noties** [comment]
Hello @biodunalfet !

It seems that `Html5Entities` cannot read Java resource file. The weird part is the _randomness_ of the error. There is a chance that your build process somehow removes `/org/commonmark/internal/util/entities.properties` file from resulting APK.

* are you using dynamic features/app bundle?
* are you using proguard?
* you are building with gradle, right?

It seems that the cause of the issue lies somewhere in-between:
* build-process
* play store publishing
* on-device distribution

I've tried you markdown input on my devices with sample application and it works fine. So, it should not be markdown specific.

**Comment by biodunalfet** [comment]
@noties Yes, I am using app bundles. I don't use proguard. I'm building with gradle.

**Comment by noties** [comment]
Hello @biodunalfet !

Well, I think there is a big chance that app-bundle is at fault here. What _splits_ do you use (cpu, density) and can you see the pattern with the devices that are affected (for example x86 xxhdpi)? Anyway, you can download actual splits from play store and inspect APKs manually - check that there is a file in your APK: `/org/commonmark/internal/util/entities.properties` in the root directory (Android Studio built-in APK analizer would suffice). You also can build splits locally via [bundletool](https://developer.android.com/studio/command-line/bundletool).
