### ISSUE TITLE
StrongEmphasisSpanFactory should use StyleSpan

### ISSUE THREAD

**Issue by badoualy** [noties/Markwon#132]
* **Markwon version**:  3.0.1

Current implementation is using the custom `StrongEmphasisSpan` which is only applying `setFakeBold` to the `Paint`. This behavior is incomplete, you can check `StyleSpan` for references.

You need to apply the bold style to the typeface if possible, not doing so is causing issues when using custom font-family: the weight is not applied, and it's using the wrong font.

Using `StyleSpan` fixes this issue.

**Comment by noties** [comment]
Hello @badoualy !

It's true that `setFakeBoldText` can cause some trouble with custom typefaces. Still, I think it's the best solution in terms of performance and simplicity. If you need to use different span - just provide your own `SpanFactory`:

```java
final Markwon markwon = Markwon.builder(context)
        .usePlugin(new AbstractMarkwonPlugin() {
            @Override
            public void configureSpansFactory(@NonNull MarkwonSpansFactory.Builder builder) {
                builder.setFactory(StrongEmphasis.class, new SpanFactory() {
                    @Override
                    public Object getSpans(@NonNull MarkwonConfiguration configuration, @NonNull RenderProps props) {
                        return new StyleSpan(Typeface.BOLD);
                    }
                });
            }
        })
```

You might actually also look at the `Emphasis`, because all it does is skewing text horizontally. And maybe you custom typeface has different italics implementation.

Also, if you have some custom typeface cache - you might create own TypefaceSpan (or use a bundled with the library one - `CustomTypefaceSpan`)

**Comment by badoualy** [comment]
Yup that's what I did for now, though it would be nice to mention it in the documentation, to avoid people some headache 😂

**Comment by noties** [comment]
Definitely going to add this info in the documentation 🙌
