### ISSUE TITLE
Wrong list alignment when the TextView is aligned in center and a link is tapped

### ISSUE THREAD

**Issue by jeslat** [noties/Markwon#137]
* **Markwon version**: 3.0.2

Hi, when inside a TextView with `gravity="center_horizontal"` we try to render a list with some link inside it, when the user taps on the link all the text move to the left. 

Expected: the text is maintained in the same place when the user taps the link.
Actual: the text moves to the left when the user taps the link.

I've created a repository with a simple example where you can see the problem and reproduce it: https://github.com/jeslat/MarkwonTest

**Comment by noties** [comment]
Hey @jeslat !

It's an interesting issue. From my quick investigation - I think I've found the cause of this - `LinkMovementMethod`. Somewhere inside of it it calls `TextView.scrollTo`. And it works somewhat properly if text alignment is **not** `center_horizontal`. If it is - internal calculations are _off_ by the scroll amount that one can see in the GIF in your repository. I think it's an Android bug, and it definitely should be reported (if it's not already). Anyway, meanwhile you can try this:

* Add [better-link-movement-method](https://github.com/saket/Better-Link-Movement-Method) to your project
* Create a subclass of `TextView` that ignores all the calls to `scrollTo` (your text-view should not scroll anyway instead its parent should):

```java
public class NoScrollTextView extends TextView {

    {...}

    @Override
    public void scrollTo(int x, int y) {
        // no scroll
    }
}
```

* set the movement method before applying markdown: `textView.setMovementMethod(BetterLinkMovementMethod.getInstance());`

I tested it and it worked. Of cause there must be other solutions (maybe subclassing `LinkMovementMethod` directly), but right now I cannot dig any further.

By the way, the actual scroll, as I see it, happens when link is highlighted... 

Anyway, really good find 👍

**Comment by jeslat** [comment]
Thanks @noties for the fast answer
