### ISSUE TITLE
Latex formulas cannot render inside tables

### ISSUE THREAD

**Issue by ringosham** [noties/Markwon#158]
* **Markwon version**: 4.1.0
* **Markwon Latex extension**: 4.1.0
* **Markwon Table extension**: 4.1.0

1. Please specify expected/actual behavior
Formulas should render inside tables.
![Annotation 2019-08-23 144515](https://user-images.githubusercontent.com/7325740/63597220-d764bf80-c5b4-11e9-8915-1df632818474.png)
2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

Code
```java
Markwon markdown = Markwon.builder(this)
                .usePlugin(JLatexMathPlugin.create(50))
                .usePlugin(TablePlugin.create(this))
                .build();
```
Markdown
```md
--- | a | b
--- | --- | ---
mean | $$ \mu $$ | $$ \bar{x} $$
```

**Comment by ringosham** [comment]
Nevermind, you have to start formulas on the first character on the first line.

**Comment by noties** [comment]
Hello @ringosham !

Well, it's not _that_. The thing is - tables are really a hack because `TextView` does not support multiple columns. What it does - renders table cell content manually. This comes with limitations which are stated in [documentation](https://noties.io/Markwon/docs/v4/ext-tables/#theme). They might be not emphasized enough, I agree. In short - what content is display correctly in a Toast (for example, by calling `Toast.makeText(context, markwon.toMarkdown(markdown), Toast.LENGTH_LONG).show();`) should be displayed correctly in a table cell. Currently there is no way to display images and tables in such case. And as `ext-latex` uses images underneath, it also cannot be displayed in a table. This comes from the fact that both images and tables must have a way to invalidate widget in which they are displayed (as they _async_ and have result after spans are rendered in a widget).
