### ISSUE TITLE
How to add padding to code block?

### ISSUE THREAD

**Issue by ursusursus** [noties/Markwon#169]
Hi,
Im trying to style code / codeblock. I'd like to lower the font size and add padding around it, while preserving the original height. Or atleast left right paddings, I dont like that the bounding box wraps the text with 0 padding.

Basically want this
https://i.imgur.com/TYA97EF.png

Is this possbile?

**Comment by noties** [comment]
Hello @ursusursus !

I'm afraid that what you want cannot be done with spans only (unfortunately). Instead you must update how TextView renders code spans. To get an idea of how this can be done look at this [repo](https://github.com/kingideayou/MarkwonCodeEx/tree/master/code_extension). It is a bit outdated (for older Markwon version), but the concept still stands.

Now, let me explain a bit. We can change text size of code nodes easily with `MarkwonTheme`. But this won't affect background, as it is drawn for the whole line (this is why there are no gaps between lines). This is a limitation of spans - it cannot _easily_ detect actual line height (excluding additional space). But, for the sake of argument, let's assume we have line height. Then, a span must have an access to Canvas to draw actual background. But not all spans have access to it. For example, `LeadingMarginSpan` has it, but it must start at the beginning of a paragraph (line start) otherwise it won't be used. So it's not applicable to inline code (that can start at any position of text). Then, there is a `ReplacementSpan` with access to Canvas. But it must draw all the text by itself (including line breaks!) which is not what you want. So, the only option is to draw background by yourself by creating own `TextView`. But wait, there is another thing - text vertical alignment! If your text sizes won't match then you would naturally want to align vertically. And, as you might expect, there is no easy way to do so. You can play with `TextPaint.baselineShift` property (the only option that I had found), but how to calculate an actual value for this property is a beast of itself and I still could not crack it.

Anyway, if you pursue this Android text rendering quest I wish you good luck and only ask to keep this issue updated about your findings 🙌

**Comment by ursusursus** [comment]
Oh man.

Btw iA writer (https://play.google.com/store/apps/details?id=net.ia.iawriter) looks like it has it working https://i.imgur.com/Dd6yzDx.png

Is it a custom textView really?

**Comment by noties** [comment]
If it uses native text rendering - most likely. But I see that most of the markdown apps on Android just go with WebView which opens up the CSS with which this task becomes _relatively_ easy. Also notice the rounded corners of background - you cannot achieve that with spans, but must go with custom drawing

**Comment by ursusursus** [comment]
Whats native text rendering? canvas.drawText?

**Comment by noties** [comment]
Native in this case - rendered via `TextView` (or any other _native _Android ways including `canvas.drawText`), as opposed to WebView with HTML, CSS and JS

**Comment by ursusursus** [comment]
Btw if you're familiar with Dank reddit app. He has a fork of your lib there, however I dont see much differences from your CodeSpan etc.

https://github.com/saket/Dank/blob/39beb5bdd01bb7e1203847be4b2dde5c2fb192fc/markdownhints/src/main/java/me/saket/dank/markdownhints/spans/IndentedCodeBlockSpan.java

https://github.com/saket/Dank/blob/39beb5bdd01bb7e1203847be4b2dde5c2fb192fc/markdownhints/src/main/java/me/saket/dank/markdownhints/spans/InlineCodeSpan.java

Yet it produces this
![Screenshot_20191011-205925](https://user-images.githubusercontent.com/1503402/66677585-3d42fe80-ec6a-11e9-8f25-6c71ce1fa608.png)

Any idea how? I've tweeted at him, still waiting for reply

**Comment by noties** [comment]
I do not see anything that is not supported by Markwon out-of-box. 


Are you talking about these code blocks _with padding_ ![screen](https://user-images.githubusercontent.com/7278986/66715851-e73c9b00-edd0-11e9-84da-c98f7354db57.png)?

**Comment by ursusursus** [comment]
Yes, and inlines seem ti have padding left right too

**Comment by noties** [comment]
By default inline code has _padding_ &mdash; a space character before and after code content. Are you sure you are missing it?

**Comment by noties** [comment]
Code block always start with a paragraph so `LeadingMarginSpan` can be used

**Comment by ursusursus** [comment]
hm, so LeadingMarginSpan also adds padding to the end?

**Comment by noties** [comment]
No, unfortunately there is no span that can add a _padding_ at the end. `LeadingMarginSpan` as the name suggests only controls the start of a paragraph (leading margin itself).

**Comment by ursusursus** [comment]
Yes thats what confuses me, since Dank has end padding too and I dont see the markwon ext there. Ill dig deeper

**Comment by ursusursus** [comment]
Yes you were right, there is no proper padding in Dank, only out of the box markwon

**Comment by noties** [comment]
Just out of curiosity - did you find a solution to your problem?

**Comment by ursusursus** [comment]
No, I left it be unpadded, as its not that often that there is full line in code blocks, and not worth the effort of custom textview

**Comment by noties** [comment]
Wise decision 😄

**Comment by ursusursus** [comment]
And praying Compose fixes it 😃

**Comment by noties** [comment]
You lost me here... how Compose can possibly fix that?

**Comment by ursusursus** [comment]
That its going to become its own "view" in flow layout thing etc. I think there already is something like that in the sample app they provide, compose news or somethijg like that

**Comment by agnostic-apollo** [comment]
>By default inline code has padding — a space character before and after code content. 

Hi @noties, how would one remove this inline code padding? What adds it? Will `BackticksInlineProcessor` be required?  I want to preserve original content and not add or remove any spaces, even if content is just a single space. Thanks

https://github.com/noties/Markwon/blob/v4.6.2/markwon-inline-parser/src/main/java/io/noties/markwon/inlineparser/BackticksInlineProcessor.java

**Comment by noties** [comment]
Hello @agnostic-apollo ,

you do not need to deal with inline parsing, a simple visitor for `Code` would do - https://github.com/noties/Markwon/blob/6f8b8e71f57ffd9b25cc02f99a301b4f06550f77/markwon-core/src/main/java/io/noties/markwon/core/CorePlugin.java#L270

```kotlin
val markwon = Markwon.builder(context)
  .usePlugin(object : AbstractMarkwonPlugin() {
    override fun configureVisitor(builder: MarkwonVisitor.Builder) {
      builder.on(Code::class.java) { visitor, node ->
        val length = visitor.length()
        visitor.builder().append(node.literal)
        visitor.setSpansForNodeOptional(node, length)
      }
    }
  })
  .build()
```

**Comment by agnostic-apollo** [comment]
Thanks a lot @noties! It's working. Thanks for the internal code link too, my search seems to have failed me ;)
