### ISSUE TITLE
How to display image from android file system?

### ISSUE THREAD

**Issue by j-roskopf** [noties/Markwon#190]
* **Markwon version**: 4.2.0

Based on the type of scheme handlers I see in the readme, it is possible to load an image from the assets folder (via `FileSchemeHandler`) - but my image does not live in the assets folder, it is living on the phone's file system.

Is it possible to display an image with Markwon from the file system?

**Comment by noties** [comment]
Hello @j-roskopf !

`FileSchemeHandler` takes care of the `file://` scheme in general. Loading images from `assets` folder is just a configuration option and it is only used when image URL looks like: `file:///android_asset/${YOUR_URL}`. In other cases supplied URL will be converted to an InputStream and passed along to `MediaDecoder`.

Please note that `FileSchemeHandler` does not deal with permissions (if your app can access file system for example), so this must be done by yourself.

**Comment by j-roskopf** [comment]
Thanks for the reply! that is good to hear that I was on the right track, I'm still having some trouble loading an image though with this markdown and this code - is there something else I am doing wrong? Current behavior is nothing is happening - and I don't see any errors in the console 

```
        Markwon.builder(holder.noteItemEditor.context).usePlugin(ImagesPlugin.create())
            .usePlugin(object : AbstractMarkwonPlugin() {
                override fun configure(registry: MarkwonPlugin.Registry) {
                    registry.require(
                        ImagesPlugin::class.java
                    ) { imagesPlugin -> imagesPlugin.addSchemeHandler(DataUriSchemeHandler.create()) }
                }
            }).build().setMarkdown(textView, markDown)
```

`<center>![Image](file:///storage/emulated/0/Download/dog-landing-hero-lg.jpg)</center>`

I have verified my app has the correct file storage permissions

**Comment by noties** [comment]
You code doesn't use `FileSchemeHandler`, so at least you should see 😄 

```javastacktrace
E/MARKWON-IMAGE: Error loading image: file:///storage/emulated/0/Download/dog.jpg
    java.lang.IllegalStateException: No scheme-handler is found: file:///storage/emulated/0/Download/dog.jpg
        at io.noties.markwon.image.AsyncDrawableLoaderImpl$1.run(AsyncDrawableLoaderImpl.java:133)
```

You can use `MARKWON-IMAGE` tag to filter for images log messages in logcat

**Comment by j-roskopf** [comment]
I was never able to get any logs from markwon to be visible in logcat, but I did end up finding the issue. Removing the `<center> </center>` allowed the image to display correctly with the following code 

The markdown trying to be loaded is similar to above just minus the `<center> </center>`

```
        Markwon.builder(holder.noteItemEditor.context)
            .usePlugin(ImagesPlugin.create { plugin -> plugin.addSchemeHandler(FileSchemeHandler.create())})
            .build()
            .setMarkdown(holder.noteItemEditor, noteEntity.markDown)
```

My textview also lived in a RecyclerView if that matters / mattered at all.

Anywho - thanks for the help! Please feel free to close

**Comment by noties** [comment]
Hello @j-roskopf !

You are right. `<center>` is the culprit here along with the HTML support in commonmark in general. You can take a look at [commonmark-dingus](https://spec.commonmark.org/dingus/?text=%23%20Block%20(center)%0A%3Ccenter%3E!%5BImage%5D(file%3A%2F%2F%2Fdog.jpg)%3C%2Fcenter%3E%0A%0A%23%20Inline%0A%3Cspan%3E!%5BImage%5D(file%3A%2F%2F%2Fdog.jpg)%3C%2Fspan%3E%0A%0A%23%20Block%20(this%20works)%0A%3C!--%20put%20new%20lines%20to%20make%20this%20work%20--%3E%0A%3Ccenter%3E%0A%0A!%5BImage%5D(file%3A%2F%2F%2Fdog.jpg)%3C%2Fcenter%3E%0A%0A) to better see the difference between HTML blocks and inlines and how they are treated by the commonmark.

In short, even you don't use `HtmlPlugin`, commonmark still parses HTML content. This content is just discarded. So, as commonmark sees this literal: `<center>![Image](#)</center>` the whole contents are just ignored. 

---

A few side notes for `RecyclerView` usage:
1. Pre-build `Markwon` instance (building with each `bind` call can be expensive and 100% wasteful)
2. Cache parsed markdown (so, actual parsing and rendering is done once, then cached result is used), `Spanned cache = markwon.toMarkdown(md)` then `markwon.setParsedMarkdown(textView, cached)`
3. Apply `NoCopySpanFactory` to your TextView when view is built in `onCreateViewHolder`: `textView.setSpannableFactory(NoCopySpannableFactory.getInstance())`

**Comment by j-roskopf** [comment]
I am currently doing one and two, just didn't reflect in the code snippet as I was trying to debug the image issue, but good to know I was on the right track with it! the third one I am not though - thanks for the tip :)
