### ISSUE TITLE
HTML <img /> tag will swallow the first newline after it

### ISSUE THREAD

**Issue by drakeet** [noties/Markwon#212]
* **Markwon version**: _4.3.0-SNAPSHOT_

As the title says, whether there is no blank line after the image, there will be no blank line in the rendering result. But if we don't use HTML but the Markdown IMG tag, there is no such problem, so I suspect that all HTML tags may have similar problems. Source content:

<img src="https://user-images.githubusercontent.com/5214214/76531740-a1375080-64b0-11ea-8f86-377bd00fb68f.png" width=360 />

The result:

<img src="https://user-images.githubusercontent.com/5214214/76531794-af856c80-64b0-11ea-902d-4c77c1a02708.png" width=360 />

BTW, the inline LaTeX in 4.3.0-SNAPSHOT works great! Thank you very much!

**Comment by drakeet** [comment]
@noties I'm not sure where this problem is caused, I think you are more familiar with it, maybe you can point out the source of the problem faster, and I can help to fix it and submit a PR.

**Comment by noties** [comment]
Hello @drakeet !

It seems to be a _common_ commonmark thing (no pun intended):

```markdown
## Try CommonMark

Markwon IMG:

![](https://upload.wikimedia.org/wikipedia/it/thumb/c/c5/GTA_2.JPG/220px-GTA_2.JPG)

New lines...

HTML IMG:

<img src="https://upload.wikimedia.org/wikipedia/it/thumb/c/c5/GTA_2.JPG/220px-GTA_2.JPG">

New lines
```

You can try it in [dingus](https://spec.commonmark.org/dingus/). For me it yields the same result as you'd posted. So there must be some specification about this. I think this happens because markdown and HTML do not share the same logic about whitespace (HTML _consumes_ all available white space, try adding more new lines after `<img>` you will see that they all are consumed/ignored)

**Comment by drakeet** [comment]
Thank you! @noties It's helpful, the HTML of its result:

```html
<h2>Try CommonMark</h2>
<p>Markwon IMG:</p>
<p><img src="https://upload.wikimedia.org/wikipedia/it/thumb/c/c5/GTA_2.JPG/220px-GTA_2.JPG" alt="" /></p>
<p>New lines...</p>
<p>HTML IMG:</p>
<img src="https://upload.wikimedia.org/wikipedia/it/thumb/c/c5/GTA_2.JPG/220px-GTA_2.JPG">
<p>New lines</p>
```

We can see the `<img />` is not wrapped in a `<p />`

**But on GitHub, the Markdown works as expected:**

## Try CommonMark

Markwon IMG:

![](https://upload.wikimedia.org/wikipedia/it/thumb/c/c5/GTA_2.JPG/220px-GTA_2.JPG)

New lines...

HTML IMG:

<img src="https://upload.wikimedia.org/wikipedia/it/thumb/c/c5/GTA_2.JPG/220px-GTA_2.JPG">

New lines

---

So maybe this should be a bug of commonmark? Do we have a workaround to fix it in advance?

**Comment by noties** [comment]
Hello @drakeet !

I'm not sure if it is a bug in commonmark. From their [spec](https://spec.commonmark.org/0.29/#html-blocks) it seems to be working as intended (we fall into the `7` case). So, it sees the HTML tag open and starts _markdown_ HTML block. Then it sees the new line and closes the block. A new line is not added after this block because markdown blocks are not placed inside paragraphs (`<p>`). 

Possible _oversight_ from commonmark perspective may come from the lack of awareness about _self-closing_ and/or _void_ tags (`<img>` can be both). But I think the specification tried to be distant from actual HTML semantics, thus it introduced (quite questionable in my opinion) own definition of HTML inlines and blocks that has very little to do with actual HTML inlines and blocks. 

In this case commonmark _should've_ treated `img` tag as _markdown_ HTML inline, which would created expected text layout structure. And here actually lies a quick workaround - try adding a closing `img` tag on the same line:

```html
<img src="https://upload.wikimedia.org/wikipedia/it/thumb/c/c5/GTA_2.JPG/220px-GTA_2.JPG"></img>
```

I know it is somehow discouraged to use `img` closing tags. Still it is valid and it creates proper text layout in both dingus and `Markwon`

**Comment by drakeet** [comment]
Got it, thank you so much for your help and workaround! Currently, I think it is OK to close this issue for Markwon, or if we can do more, we can reopen this.
