### ISSUE TITLE
Spans are not parsed if they come after HTML block

### ISSUE THREAD

**Issue by Adonai** [noties/Markwon#276]
* **Markwon version**: 4.4.0

If I parse this text into Markdown with `toMarkdown` call
```
<span class="fr-video fr-draggable">

Some random stuff

</span>  
Test photos:  
![](https://images.gog-statics.com/5dcf7af84dc02726493692410070224878cf34e07826903293de85e34394bb7e_800.png)
![](https://images.gog-statics.com/4195578c74d8d69189a9102bbc39e529cdc88322e445199a231d5d7cca0e99db.jpg)
```
**It doesn't show images, at all.**

But if I change it to
```
<span class="fr-video fr-draggable">

Some random stuff

</span>  

Test photos:  
![](https://images.gog-statics.com/5dcf7af84dc02726493692410070224878cf34e07826903293de85e34394bb7e_800.png)
![](https://images.gog-statics.com/4195578c74d8d69189a9102bbc39e529cdc88322e445199a231d5d7cca0e99db.jpg)
```
Then everything works as expected.

It seems like parser somehow doesn't detect tag close as HTML block ending.
Can you please advise?

**Comment by noties** [comment]
Hello @Adonai ,

it seems to be _commonmark_ issue - you can try your input in their [dingus](https://spec.commonmark.org/dingus/) which yields the same result.

The reason is - commonmark spec assumes too much about HTML. First, it expects to be rendered in a browser (so browser would consume any HTML in markdown input and render it). And second, it introduced 2 HTML entities that are not connected with HTML (yeah, so there is no HTML parser in commonmark - HTML parsing is hard) - inline and block, which have nothing to do with HTML inline and block. So in your input `</span>` would be considered commonmark-html-block start, and contents after it - HTML literal, thus not parsed by markdown parser. It is most unfortunate, but I'm afraid this is how spec is created

**Comment by Adonai** [comment]
Outrageous. Thanks for your explanation @noties!
