### ISSUE TITLE
How to add support for custom markdown syntax?

### ISSUE THREAD

**Issue by Docile-Alligator** [noties/Markwon#277]
- **Markwon version**: 4.5.0

I want to add support for Reddit's spoiler syntax, which is >!some spoilers!<
Using this syntax will make the spoiler text has a black background color so that users will not see the text at first. They can click on the spoiler text to remove the background color to see the spoiler.
Currently plugin.addExtension doesn't support delimiters like >! and !<.

Should I create a SpoilerNode to use in builder.setFactory to append some spans?

**Comment by Docile-Alligator** [comment]
Ok. I have figured out a way to show a background color on spoiler text. But since > is used to render blockquote, it will simply override the spoiler. How to make spoiler rendering have higher priority than blockquote?

The method I use to hide spoiler text is to override afterSetText in AbstractMarkwonPlugin. I take out the text displayed in TextView and use regex to match !spoiler!<. I cannot match >!spoiler!< because blockquote removes the > at the beginning. After that, I use a BackgroundColorSpan and ClickableSpan on the spannable text to hide the spoiler.

I don't think this is a good implementation so could anyone help with this?

**Comment by noties** [comment]
Hello @Docile-Alligator ,

I think that you did it the parsing the right way (searching for `>! !<` occurrences in text). I've added a [sample](https://noties.io/Markwon/app/20200813145316) to confirm this. So, in order to not render blockquote - it is sufficient to replace `>!` in your markdown with `&gt;!`. Parser would turn this into `>!` anyway but blockquote won't be detected

**Comment by Docile-Alligator** [comment]
This works! Thank you so much!!!!

**Comment by damionx7** [comment]
Hey @noties , the spoilers tag doesnt work in tables. It shows the spoiler as it is.  What can I do to render spoilers in table ? 

![Screenshot_20210205-100454903 (1).jpg](https://user-images.githubusercontent.com/6530843/106990123-8c6c4700-676b-11eb-91f7-facca7a06ef7.jpg)

**Comment by noties** [comment]
Hello @damionx7 ,

yes, tables have limitation and accept only _static_ content. This is due to tables being drawn to canvas directly (you can take a look at `TableRowSpan` source code). Right now the only workaround is to use `markwon-recycler-table` artifact which renders markdown in a `RecyclerView` and table in a `TableLayout` where each cell is a standalone `TextView`

**Comment by damionx7** [comment]
How I can do that @noties ? Can you show some code or link to sample ?

**Comment by damionx7** [comment]
Thanks @noties
