### ISSUE TITLE
Table does not render if it's located at the end of a string

### ISSUE THREAD

**Issue by hfann** [noties/Markwon#28]
Table will not render and the whole table is missing from the output if it is the last element in a string. However, if there is any text after the table, the table will render properly. See the [attached file](https://github.com/noties/Markwon/files/1794173/tableissue.txt) for a demonstration.

**Comment by noties** [comment]
Hello @hfann !

I have investigated and found that a table is not rendered because it is represented as a single white space char, but as we have started recently _trimming_ white spaces from the end of a final result, tables were removed. The fix will be delivered in the next release. Thank you for the find!
