### ISSUE TITLE
What is the correct way to treat a token when it is insignificant?

### ISSUE THREAD

**Issue by littledot** [noties/Markwon#283]
* **Markwon version**: 4.5.0

In many inline processors such as [`AutolinkInlineProcessor`](https://github.com/noties/Markwon/blob/65309e684c68b82ded53b1f4bb8d317782b4ccc8/markwon-inline-parser/src/main/java/io/noties/markwon/inlineparser/AutolinkInlineProcessor.java#L41), when the token is insignificant, the processor will return null.

However, [`BangInlineProcessor`](https://github.com/noties/Markwon/blob/65309e684c68b82ded53b1f4bb8d317782b4ccc8/markwon-inline-parser/src/main/java/io/noties/markwon/inlineparser/BangInlineProcessor.java#L35) returns null AND resets paser's index when the token is insignificant, 

While [`CloseBracketInlineProcessor`](https://github.com/noties/Markwon/blob/65309e684c68b82ded53b1f4bb8d317782b4ccc8/markwon-inline-parser/src/main/java/io/noties/markwon/inlineparser/CloseBracketInlineProcessor.java#L38) returns a `Text` node of the token when the token is insignificant.

What is the correct way to treat a token when it is insignificant?

Also, I'm planning on writing a custom inline parser that checks the `/` character, if this info helps.

**Comment by noties** [comment]
Hello @littledot ,

the idea is to return `null` when an inline processor has no match, so further parsing can be done at the __same__ position/state. Currently `BangInlineProcessor` is the only one that also resets index because I found out that you cannot define multiple inline processors for the same character (in this case &mdash; `!`). I didn't touch other processors because I want them to be as close to the `commonmark-java` source as possible - so future improvements of `commonmark-java` can be easily merged into `inline-processor`. The whole `inline-parser` is an attempt at _modularization_ of inline parsing from the `commonmark-java`, so a lot of sources are the same (compare [AutolineInlineProcessor](https://github.com/noties/Markwon/blob/65309e684c68b82ded53b1f4bb8d317782b4ccc8/markwon-inline-parser/src/main/java/io/noties/markwon/inlineparser/AutolinkInlineProcessor.java#L41) and [InlineParserImpl.parseAutolink](https://github.com/atlassian/commonmark-java/blob/master/commonmark/src/main/java/org/commonmark/internal/InlineParserImpl.java#L610) )

In general - `BangInlineProcessor` should not reset index because this must be done automatically when `null` is returned

**Comment by littledot** [comment]
Thanks for clarifying!
