### ISSUE TITLE
Maths / custom css support

### ISSUE THREAD

**Issue by laclance** [noties/Markwon#29]
Hi there, looking at the code I understand this could be a long and complicated task but I am just wondering the possibility of supporting maths rendering (like katex) or at least custom css rules which I presume would be the main speed bumb.

**Comment by noties** [comment]
Hello @laclance !

Well, supporting math formulas is indeed a complicated task. At least if we are talking about rendering them natively. Surprisingly there are a lot of implementations for the _web_, but none that I can find for Android without usage of WebView (not so far from most markdown editors/viewers). I did find an interesting project for editing LaTeX in Java ([TeXlipse](https://github.com/eclipse/texlipse)), from which we _could_ extract the actual parsing and creation of LaTeX AST, but it's hard as it sounds and goes even further because after parsing the AST must be laid out (aka rendered). 

And adding custom CSS rules won't do any good as we do not deal with HTML at all (we do support small subset of HTML, but introducing complete HTML/CSS parser and renderer is IMO not-desired, as let's say it honestly, if you need Web technology, maybe using a Web tool for example WebView will have more positive effect as in, you know, `pick the tool for the job`).  

As always I'm linking the project that Markwon is based on: [commonmark-java](https://github.com/atlassian/commonmark-java). Currently it doesn't support LaTeX (as many other things that take over the Web), as it tries to follow the [CommonMark](http://commonmark.org/) specification, which keeps this functionality not covered. But who knows, maybe some day it will.

Still, if you have enough motivation and spare time we can discuss how to _try_ to implement this functionality. I'm leaning to extracting actual rendering to a standalone `Drawable`, which might be at help for some other projects too (shaping it as an independent library, like `MathDrawable`, or even `LatexDrawable` if we are going the hard way). But how much effort it will require I do not have even slightest idea.

Anyway, thanks for the issue, I'm keeping it open so there is no confusion about the functionality covered by this library 🙌

**Comment by laclance** [comment]
Thank you very much for your detailed response, unfortunate i do not have too much spare time so will probably use a webview implementation for the moment. I am not sure if I agree with you though that an HTML/CSS parser and renderer is not-desired. There is the Html class added Android's API level 1 and some libraries with extended capabilities but they lack the CSS support to display maths. I am far from an expert so maybe I am wrong but the webview component is rather slow and cumbersome due to the range of functionality available and maybe just a little over board if you just want to render some html and css, which is all that markdown and maths is once it has been parsed.

**Comment by noties** [comment]
Hey @laclance !

Well, ![css-is-awesome](https://bethesignal.org/wp-content/uploads/2009/06/css-is-awesome-700x375.jpg)
everyone knows it ;) It's hard to master even for browsers developers. Take a look at [specs](https://www.w3.org/Style/CSS/specs.en.html).

But I have one idea for you. There is a [service](http://www.codecogs.com/latex/eqneditor.php) which allows export of math formulas as an SVG.

For example: `x = a_0 + \frac{1}{a_1 + \frac{1}{a_2 + \frac{1}{a_3 + a_4}}}` would become:

![svg](http://latex.codecogs.com/svg.latex?x%20%3D%20a_0%20&plus;%20%5Cfrac%7B1%7D%7Ba_1%20&plus;%20%5Cfrac%7B1%7D%7Ba_2%20&plus;%20%5Cfrac%7B1%7D%7Ba_3%20&plus;%20a_4%7D%7D%7D).

Then, we could do this:

```java
@NonNull
public static String processMathFormulas(@NonNull String markdown) {

    // for example we will be using <math></math> as delimiters

    final String open = "<math>";
    final String close = "</math>";

    int index = markdown.indexOf(open);

    if (index < 0) {
        // return untouched
        return markdown;
    }

    int last = 0;
    int end;

    final StringBuilder builder = new StringBuilder();

    while (index > -1) {

        end = markdown.indexOf(close, index);
        if (end < 0) {
            throw new IllegalStateException("Unexpected state, math tag is not closed");
        }

        builder
                .append(markdown.substring(last, index))
                .append("![math](")
                .append(encodeUrl("http://latex.codecogs.com/svg.latex?" + markdown.substring(index + open.length(), end)))
                .append(")");


        last = end + close.length();
        index = markdown.indexOf(open, last);
    }

    return builder.toString();
}

@NonNull
private static String encodeUrl(@NonNull String rawUrl) {

    // https://stackoverflow.com/a/25735202/6745174
    try {
        final URL url = new URL(rawUrl);
        final URI uri = new URI(url.getProtocol(), url.getUserInfo(), url.getHost(), url.getPort(), url.getPath(), url.getQuery(), url.getRef());
        return uri.toASCIIString();
    } catch (Exception e) {
        throw new RuntimeException(e);
    }
}
```

then

```java
final String markdown = processMathFormulas(rawMarkdown);
Markwon.setMarkdown(textView, markdown);
```

This solution will require network connection though. And the linked service has free tier, but otherwise is a paid service. But as a quick solution this might work.

**Comment by laclance** [comment]
Yeah been looking into svg options but might not be worth it considering the development time performance difference between just using a webview and I also require offline use but thank you again for your response, maybe a possibility in the future.

**Comment by webserveis** [comment]
@laclance you can look this repository https://github.com/vsch/flexmark-java

**Comment by noties** [comment]
@webserveis Flexmark is a great library and in fact is a fork of Commonmark-java (on which this Markwon library is based). But I do not see how it can help with math support as I cannot find any extension/module in Flexmark that adds support for math formulas. Am I missing something?

**Comment by webserveis** [comment]
Well, if you're right, Looking deeper into the library, I see that they only refer to mathml

https://github.com/vsch/flexmark-java/issues/193

Maybe, combined with that library you could get a svg
https://github.com/mathjax/mathjax

**Comment by noties** [comment]
If someone is interested I have added a sample module that shows how to add LaTeX math to your markdown: `https://github.com/noties/Markwon/tree/v2.0.0/sample-latex-math`. It's still in development branch, but soon it will be released

**Comment by noties** [comment]
It's been released and now can be found here: [sample-latex-math](https://github.com/noties/Markwon/tree/master/sample-latex-math)
