### ISSUE TITLE
Question - Live render input during typing as far as possible

### ISSUE THREAD

**Issue by MFlisar** [noties/Markwon#293]
* **Markwon version**: 4.5.1

This is more a question for a little initial help on how to solve a problem I have - I would appreciate your input very much.

## Desired result

I would like to make an editor that does implement live preview of the input inside the input `EditText`. This means, as soon as a markdown enclosing tag is closed or a html enclosing tag is closed I want to render the markdown instead of rendering the input. Deleting inside this `EditText` should work as if the input is not rendered as markdown but as raw text.

E.g.:

Example | Input | Rendered output
--- | --- | ---
1 | `**test**` | **test**
2 | `**test*` | `**test*` or  **test*

In case 1, even though the user only sees **test** pressing the delete button should return the last character of the raw input (`*`) and not the last visible character (`t`), so pressing delete in case 1 should lead to case 2 as a result.

An example video of this process can be seen [here](https://typora.io/img/beta.mp4) inside a windows/mac application.

## Question

1. Any plans on implementing something like this inside your library?
2. As I assume not, any ideas on where I could start or any other input that would be helpful?

**Comment by noties** [comment]
Hello @MFlisar ,

sorry for late reply, hope this is still relevant.

As you can imagine writing a WYSIWYG editor is a technically advanced topic, especially on Android. And It might be a hard task to perfect. 

I personally prefer editor to contain all _special_ syntax in place with additional highlight or emphasis. This is what `markwon-editor` tries to achieve. But as you'd asked for a tip for WYSIWYG editor, as I assume using `Markwon`, we could at least try to do something.

For example, we can use `markwon-editor` with a special syntax span - the span that hides syntax:

```java
class HidePunctuationSpan extends ReplacementSpan {

  @Override
  public int getSize(@NonNull Paint paint, CharSequence text, int start, int end, @Nullable Paint.FontMetricsInt fm) {
    return 0;
  }

  @Override
  public void draw(@NonNull Canvas canvas, CharSequence text, int start, int end, float x, int top, int y, int bottom, @NonNull Paint paint) {

  }
}
```

Then we must write custom edit handlers to add special spans for markdown syntax we want to support - for strong emphasis, emphasis, code, quotes, etc. Also, unfortunately, we won't be able to leave our `HidePuntuationSpan` as-is, we will need to handle _pending_ syntax and trailing space in order to display them - otherwise they won't be visible and confusing to a user.

There are a lot of issues that I notice here and you can see my ramblings in comments in the [sample](https://noties.io/Markwon/app/sample/20200908133515) but I think there is a chance to overcome them with proper time and effort. BTW if you feel like it you could use that sample as a playground and issue a pull request when you'd finish (or during the process so we can have a discussion)

**Comment by noties** [comment]
Feel free to reopen this issue if you have more questions
