### ISSUE TITLE
How to centre the images with align=center in image tag

### ISSUE THREAD

**Issue by ankush-dcoder** [noties/Markwon#304]
* **Markwon version**: _4.6.0_

1. Please specify expected/actual behavior
```html
<img align="center" width="100" src="http://www.fillmurray.com/100/100">
```
Should align the image at center.

https://github.com/noties/Markwon/issues/139, this provides a way to align images at center, but we do not want to introduce this for all the images, how do we support align="center" , align="left", align="right", so we can be compatible with some other render engines.

Also is there a way to calculate image width, for example if image width > 600px then render at center else render at left.

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)
Use `<img align="center" width="100" src="http://www.fillmurray.com/100/100">` in a Markwon rendered text and the image gravity stays on left.

**Comment by noties** [comment]
Hello @dcodermobile ,

you need to look up the [TagHandler](https://noties.io/Markwon/docs/v4/html/#taghandler) in order to customize how your render certain HTML tags. And take a look at how the builtin [image tag handler](https://github.com/noties/Markwon/blob/master/markwon-html/src/main/java/io/noties/markwon/html/tag/ImageHandler.java) behaves to override its behavior to match your requirements
