### ISSUE TITLE
Can Markwon produce HTML output?

### ISSUE THREAD

**Issue by klm1** [noties/Markwon#324]
* **Markwon version**: 4.6.0

Can Markwon be used directly to produce HTML output (as an alternative to Spannables)? If not, is it possible to use the commonmark-java embedded in the Markwon package, or must  commonmark-java be included again separately?

**Comment by noties** [comment]
Hello @klm1 ,

[commonmark-java](https://github.com/commonmark/commonmark-java) provides HTML renderer which you can use. Markwon was created as another frontend to commonmark-java's HTML renderer to be more performant on Android specifically. But you don't need to use Markwon in order to use commonmark-java on Android if you only need HTML output.  

Either way you can an explicit dependency for commonmark-java. Just be sure that versions are compatible

**Comment by klm1** [comment]
Hi @noties — thanks for that info.

Ok great, so if the intent is to produce both Spannables **and** HTML in an Android project, then **both** Markwon and commonmark-java should be included as dependencies. And if (for example), Markwon 4.6.0 is used, then the matching commonmark-java version would be 0.13.
