### ISSUE TITLE
Setting click listeners for mentions (@) and hashtags(#)

### ISSUE THREAD

**Issue by chrisbarth01** [noties/Markwon#342]
* **Markwon version**: _{4.6.2}_

I'm working on an app that has to do with mentions and hashtags. I'm using a [social textview library](https://github.com/hendraanggrian/socialview) which comes with a textview that highlights mentions and hashtags. The Issue is that I can't use this textview to show the markdown content. However, it works very well when using the normal textview. Is there any way you can support other textviews? **Or maybe a way to set onclick listeners for hashtags and mentions?**

**Comment by noties** [comment]
Hello @chrisbarth01 ,

there is no requirement for a `TextView` from `Markwon` to display markdown content. You can use any `TextView` as long as it supports spanned content. The problem here lies in the [SocialView](https://github.com/hendraanggrian/socialview) library that [removes all the spans](https://github.com/hendraanggrian/socialview/blob/07078840be44da1c7cd737252206ce1a27474371/socialview/src/com/hendraanggrian/appcompat/widget/SocialViewHelper.java#L384) from a `TextView`. So, in order to display markdown content in one of the `SocialView`'s widgets, they must support spanned content that comes from other places except their own (they also use spans to display mentions). There is little we can do to change how they treat spans. But luckily this functionality has been already covered by multiple samples (those do not require any 3rd party libraries):

* [GithubUserIssueOnTextAddedSample](https://github.com/noties/Markwon/blob/205ae7b47a66d7bd33a0b21c7c9105929cd8a117/app-sample/src/main/java/io/noties/markwon/app/samples/GithubUserIssueOnTextAddedSample.java)
* [GithubUserIssueInlineParsingSample](https://github.com/noties/Markwon/blob/205ae7b47a66d7bd33a0b21c7c9105929cd8a117/app-sample/src/main/java/io/noties/markwon/app/samples/GithubUserIssueInlineParsingSample.java)

There is also an option to preprocess entire raw markdown input and substitute all mentions with regular markdown links (via `MarkwonPlugin.processMarkdown` method). There is no code sample that features this, but most of the code can be shared with the `GithubUserIssueOnTextAddedSample` sample, which should give you enough to get started

**Comment by chrisbarth01** [comment]
Thanks for the quick response @noties.
Here's something...

```private void setLink(@NonNull MarkwonVisitor visitor, @NonNull String destination, int start, int end) {

    // might a simpler one, but it doesn't respect possible changes to links
//            visitor.builder().setSpan(
//                    new LinkSpan(visitor.configuration().theme(), destination, visitor.configuration().linkResolver()),
//                    start,
//                    end
//            );

    // use default handlers for links
    final MarkwonConfiguration configuration = visitor.configuration();
    final RenderProps renderProps = visitor.renderProps();

    CoreProps.LINK_DESTINATION.set(renderProps, destination);

    SpannableBuilder.setSpans(
      visitor.builder(),
      configuration.spansFactory().require(Link.class).getSpans(configuration, renderProps),
      start,
      end
    );
  }```

This sets the click to open external links. I rather want to open another activity on my app and pass the username/hashtag through ```intent.putExtra()```

I've tried to work this out but it rather crashes.

**Comment by chrisbarth01** [comment]
Sorry I has to edit that so much times...

**Comment by noties** [comment]
It seems that crash occurs when you click the link? In that case you might be passing invalid link, like `@user`, which Android cannot open and fails with `ActivityNotFoundException`. You can process links before they are opened with `LinkResolver`, for example:

```java
final Markwon markwon = Markwon.builder(context)
  .usePlugin(new AbstractMarkwonPlugin() {
    @Override
    public void configureConfiguration(@NonNull MarkwonConfiguration.Builder builder) {
      builder.linkResolver(new LinkResolverDef() {
        @Override
        public void resolve(@NonNull View view, @NonNull String link) {
          // here you can process your link, the `condition` depends on format that you
          //  create your mentions
          if (/*condition*/) {
            
          } else {
            // pass to super to open other links
            super.resolve(view, link); 
          }
        }
      });
    }
  })
  .build();
```

**Comment by chrisbarth01** [comment]
It seems I confused you a bit. Here's what I want; any mention/hashtag will in no condition load a URL in the browser, instead when a mention is clicked, it passes the username to activityA by using `intent.putExtra("key", username)`.  activityA then automatically searches for the username(this part is mine). Also, the same case applies when a hashtag is clicked, just that hashtags will open activityB and search... I have this helps to understand.

**Comment by chrisbarth01** [comment]
Also, I noticed that there's no click listener for hashtags (even when I try to replicate the sample code), only mentions are underlined and clickable.

**Comment by chrisbarth01** [comment]
I discovered where the error was coming from
```
Pattern.compile((#\\d+)|(@\\w+)), Pattern.MULTILINE)
```
On my end, this works
```
Pattern.compile((#\\w+)|(@\\w+)), Pattern.MULTILINE)
```

When it's corrected, hashtags can be clicked. 

# Note
**since I've resolved all the issues, I'd like to close this issue**.
Thanks for the support @noties. However, I'm having trouble displaying images so I guess I'll have to open a different issue for that.

**Comment by noties** [comment]
Just to clarify:

* `#\\d+` matches hash and a number, for example an issue on Github: #342
* `#\\w+` matches hash a _word_ character - alphanumeric and underscore, for example: `#hello_123`

**Comment by chrisbarth01** [comment]
I just checked and using `#//w+` covers up both for #342 and #word (in my code).
