### ISSUE TITLE
Connecting rows and/or columns in tables

### ISSUE THREAD

**Issue by kalucky0** [noties/Markwon#347]
* **Markwon version**: 4.6.2

I'm trying to create colspans in my table. Markdown doesn't support that natively, so I will probably have to introduce some custom syntax. How can I do that? 

![obraz](https://user-images.githubusercontent.com/10831698/112977333-36f25c00-9156-11eb-9f44-426533b8cf80.png)

**Comment by noties** [comment]
Hello @kalucky0 ,

to add support to markdown you will need to define your syntax and create a `BlockParser`. If your syntax will be _close_ to tables, then you can see how `commonmark` does it - `TableBlockParser`. Otherwise actual implementation of block parser will depend upon syntax that you'd use.

As for displaying such tables you could _enhance_ `TableRowSpan` to allow column spans or go with a standalone widget - `TableLayout` or any other _grid-like_ widget supporting column spanning and use it with `markwon-adapter` (which renders markdown in a `RecyclerView`) - for this you can inspect `TableEntry` class to see how it handles `TableLayout`
