### ISSUE TITLE
SoftBreakAddsNewLinePlugin don't work.

### ISSUE THREAD

**Issue by maitolab** [noties/Markwon#353]
* **Markwon version**: 4.6.2

The text still show 2 lines with code as below

`public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        final Markwon markwon = Markwon.builder(this)
                .usePlugin(new AbstractMarkwonPlugin() {
                    @Override
                    public void configureVisitor(@NonNull MarkwonVisitor.Builder builder) {
                        builder.on(SoftLineBreak.class, new MarkwonVisitor.NodeVisitor<SoftLineBreak>() {
                            @Override
                            public void visit(@NonNull MarkwonVisitor visitor, @NonNull SoftLineBreak softLineBreak) {
                                visitor.forceNewLine();
                            }
                        });
                    }
                })
                .usePlugin(SoftBreakAddsNewLinePlugin.create())
                .build();
        TextView txt = findViewById(R.id.text);
        markwon.setMarkdown(txt,"12\n\n\n\n\n\n\n\n\n\n\n34");
    }
}`

Could you let me know if there is any missing?

**Comment by maitolab** [comment]
![image](https://user-images.githubusercontent.com/11642429/114435106-fed72880-9bed-11eb-9f64-5703b79eaab6.png)

**Comment by maitolab** [comment]
![image](https://user-images.githubusercontent.com/11642429/114435274-30e88a80-9bee-11eb-9c3c-935e33a6a454.png)

**Comment by noties** [comment]
Hello @maitolab ,

your image cannot be displayed. But I think I know what is your issue. As per [commonmark specification](https://spec.commonmark.org/0.29/#hard-line-breaks) additional _hardline breaks_ are collapsed to produce at most one hard break. Current specification does not allow multiple empty new lines. To overcome this you can use `HtmlPlugin` along with `<br>` tags inside your markdown. 

There is also an _experimental_ solution that involves custom inline parsing processor. But due to planned `commonmark-java` version update this experimental solution might not be valid soon. Would you be still interested in such solution?

**Comment by maitolab** [comment]
@noties Thanks for your answer. This is a simulator. 
We have a edittext to enter text then format and display in textview. Then we can not insert <br> to text.
If you use enter in keyboard, it will be "hardline breaks"?

**Comment by noties** [comment]
Two of more of new line characters ("enter" in keyboard) will be considered a "hardline break"

**Comment by shubham696** [comment]
@noties @maitolab can you guys gave the example of using HtmlPlugin with <br>

**Comment by maitolab** [comment]
@shubham696 We need to add plugin
` private static final Markwon markwon = Markwon.builder(WAAFI.getContext())
            .usePlugin(StrikethroughPlugin.create())
            .usePlugin(HtmlPlugin.create())
            .build();`
and then replace break line as below 

`String body = body.replace("\n", "<br/>");
CharSequence result = markwon.toMarkdown(body);`
