### ISSUE TITLE
Support footnote links

### ISSUE THREAD

**Issue by damionx7** [noties/Markwon#360]
* **Markwon version**:  4.6.2

Hey @noties. It's more of a feature request. Can markwon support [footnotes](https://www.markdownguide.org/extended-syntax/#footnotes) or maybe how can i implement footnote links ?

```
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: This is the first footnote.

[^bignote]: Here's one with multiple paragraphs and code.
```
In the above example, clicking on [^1], scrolls to to bottom [^1]: This is the first footnote.

**Comment by damionx7** [comment]
Used processMarkdown to add custom link and then parsed custom link in fragment. 
```java
public class FootnotePlugin extends AbstractMarkwonPlugin {

  public FootnotePlugin () {}

  @NonNull
  @Override
  public String processMarkdown (@NonNull String markdown) {
    markdown = PATTERN_FOOTNOTE
        .matcher(markdown)
        .replaceAll("<sup>[$1](footnote://$1)</sup>");
    return markdown;
  }
}
```

Is there any better solution than this ?

**Comment by damionx7** [comment]
I guess the `[comment]: comment` format clashes with the footnote format `[^footnote]: text`. How to prevent this ?

when footnote is detected as comment, it is not shown in markdown.

**Comment by noties** [comment]
Hello @damionx7 ,

the `[comment]: comment` markdown is actually a link reference, for example:

```markdown
<!-- the [link] would become [link](https://example.com) -->
This is a [link]

[link]: https://example.com
```

And footnotes indeed are clashing with those. Unfortunately the link references are _hardcoded_ into the parser, so it is not easy to add support for footnotes with current syntax

**Comment by damionx7** [comment]
Thanks @noties. Guess you were on vacations.  One quick question though, can this somehow be overriden ? Any hint or guide would be helpful.

**Comment by noties** [comment]
Hello @damionx7 ,

yeah, sorry, I was unavailable. I don't think it is possible to override default handling of reference links within the parser itself. There are just too many parts to consider. If you are interested you can take a look at the `LinkReferenceDefinitionParser` in the `commonmark-java` project. And related `ParagraphParser` and `DocumentParser` parsers. Adding footnotes support would require a major change to all these components. 

I guess this is where `commonmark-java` inflexibility starts to play a role. `Markwon` has been relying on `commonmark` internals in order to tweak its parsing and make it more flexible. But lately they had changed internals in order to add support for source positions (unfortunately they are not suitable for editors, so good for nothing really). And this left `Markwon` behind as change is a bit more that I had anticipated before. Right now I'm seriously consider moving to other parsing stack, but still not sure if an abstract parsing layer should be added (so backends could be changed) or a different engine should be solely used or, finally, writing own solution for parsing. 

Anyway, right now I see conceptually only one solution to the footnotes. Preprocess raw markdown and do no rely on parser at all. For example it is no uncommon for footnotes to be styled (_marked_) so you would want to run `Markwon` other then also. Something along these lines (pseudocode):

```kotlin
// matcher to match `[^1]` links to actual footnote contents
val matcher = referencesMatcher(markdown)
while (matcher.find() {
  val content = findContent(matcher, markdown)
  // content is found `[^1]: My contents`
  if (content != null) {
    // replace link `[^1]` so parser do not handle it
    replaceFootnoteLink()
    // footnote contents can be markdown itself, so parse it
    val footnote = markwon.toMarkdown(content)
    addFootnote(footnote)
  }
}
```

1) find all footnote links in text `[^1]`
2) check if those have footnote content `[^1]: **Footnote** content`
3) exclude those from being parsed (but still be referenced after parsing, important thing to decide on)
4) find a way to display footnote and handle clicks on it (or other way of handling them altogether)
