### ISSUE TITLE
Table loosing content

### ISSUE THREAD

**Issue by Sternagfonkel** [noties/Markwon#366]
* **Markwon version**: 4.6.2

I try to render a markdown string including a table in an android notification using the table plugin. I know the support for notifications is limited according to [this example](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/notification/NotificationSample.java) you provide. If a markdown element can't be displayed in the notification, it would be sufficient to just display the pure text. This seems to work quiet good by just calling `toMarkdown()` and passing the result to the notification. Except for tables. If `toMarkdown()` is called, the text content of the table is (somehow) gone and therefore nothing of the table (except the line breaks) is displayed in the notification.
![Screenshot_20210814_181530](https://user-images.githubusercontent.com/87871070/129452835-6e07589a-4869-4568-a9f7-a8e0ed8becfe.png)
I also tried to add `builder.setFactory(TableRow.class, ((configuration, props) -> null))` and similar to exclude tables deliberately, but nothing changed.
Am I doing something wrong? Would be great to preserve the table content (or even better, display the table as table inside a notification ;)). Thanks for you support!

**Comment by noties** [comment]
Hello @Sternagfonkel ,

unfortunately tables cannot be displayed in a notification. Notification allows only _system_ spans and system does not have any equivalent for tables.

What you see - tables content gone - is expected as tables are drawn on canvas directly. A ` ` character is added to text and a special replacement span is set for it - which actually draws row content. Notifications does not allow such content to be displayed.

In order to preserve table text content you can use a custom plugin. Do not use `TablePlugin` - instead add tables parsing in the `configureParser` method. This will effectively parse tables and just add cell content to the text content:

```java
final Markwon markwon = Markwon.builder(context)
  .usePlugin(/*your other plugins*/)
  .usePlugin(new AbstractMarkwonPlugin() {
    @Override
    public void configureParser(@NonNull @NotNull Parser.Builder builder) {
      builder.extensions(Collections.singleton(TablesExtension.create()));
    }
  })
  .build();
```

You might also want to add a new line after `TableRow` and `TableHead` nodes and a space after `TableCell`:

```java
.usePlugin(new AbstractMarkwonPlugin() {
  @Override
  public void configureParser(@NonNull @NotNull Parser.Builder builder) {
    builder.extensions(Collections.singleton(TablesExtension.create()));
  }

  @Override
  public void configureVisitor(@NonNull @NotNull MarkwonVisitor.Builder builder) {
    builder
      .on(TableRow.class, this::visitRow)
      .on(TableHead.class, this::visitRow)
      .on(TableCell.class, (visitor, node) -> {
        visitor.visitChildren(node);
        if (visitor.hasNext(node)) {
          visitor.builder().append(' ');
        }
      });
  }

  void visitRow(@NonNull MarkwonVisitor visitor, @NonNull CustomNode node) {
    visitor.ensureNewLine();
    visitor.visitChildren(node);
    if (visitor.hasNext(node)) {
      visitor.forceNewLine();
    }
  }
})
```

**Comment by Sternagfonkel** [comment]
Thanks for the explanation and suggestions :+1: Helped a lot to get a better understanding. Great!
