### ISSUE TITLE
Italic gets cut

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [noties/Markwon#374]
* **Markwon version**: 4.6.2
Italic gets cut: 

![Screenshot_20211118-160804](https://user-images.githubusercontent.com/10619102/142480930-5c810275-11a2-4787-b7d4-5705b6c7a117.png)

You can check this little project reproducing this: https://github.com/leandroBorgesFerreira/MarkdownTest

**Comment by leandroBorgesFerreira** [comment]
Actually, you can go to the one line text and change thw width of TextView from match_parent to wrap_content and you'll see the text cut

**Comment by Mek101** [comment]
Add 1 extra space to the italics as a workaround?

**Comment by JHeikesWehkamp** [comment]
This bug was already discussed here:
https://github.com/noties/Markwon/issues/101

A solution for it was also posted. As an additional note: If you find you need a custom font instead of the default, make sure to include the italicized version of the font in your app and reference it when creating a custom TypeFace as outlined in the above thread.
