### ISSUE TITLE
Missing class org.commonmark.ext.gfm.strikethrough.Strikethrough

### ISSUE THREAD

**Issue by mochadwi** [noties/Markwon#375]
* **Markwon version**: 4.6.2

1. Please specify expected/actual behavior

Warning shown for release build type

```
Missing class org.commonmark.ext.gfm.strikethrough.Strikethrough (referenced from: java.lang.Object io.noties.markwon.html.tag.StrikeHandler.getMarkdownSpans(io.noties.markwon.MarkwonVisitor))
```

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

Running gradle task to build the apps with release build types

**Comment by noties** [comment]
Hello @mochadwi ,

this warning is shown by HTML plugin when you have no strike-through dependency added. HTML plugin by default tries to load it first and only after that fallbacks to own implementation. There is no action needed if you are satisfied with the result

**Comment by strongville** [comment]
I'd like to reopen this issue, because of some of the breaking changes made on Android Gradle Plugin 8.0.

Right now, the previous warning is treated as error if a rule for a missing class does not exist on main project or imported library. [Android Gradle Plugin 8.0 Release Notes: Enforced build option values](https://developer.android.com/build/releases/gradle-plugin#enforced-changes)

![imagen](https://github.com/noties/Markwon/assets/1476503/b499ac3c-8a2a-440e-829f-6b67d2ef91cd)

> HTML plugin by default tries to load it first and only after that fallbacks to own implementation.

If this still applies, it seems that it's just needed to add this rule for the library:
`-dontwarn org.commonmark.ext.gfm.strikethrough.Strikethrough`

The setting for `gradle.properties` to opt-out this new behavior is shown on the screenshot above, but maybe this shouldn't be needed.
