### ISSUE TITLE
Is that possible to separate margin and width of quote stripe?

### ISSUE THREAD

**Issue by gcobc12677** [noties/Markwon#399]
with this part in `BlockQuoteSpan` , as the increasing of width,
the left margin is increasing too.

```
final int left;
final int right;
{
    final int l = x + (dir * width);
    final int r = l + (dir * width);
    left = Math.min(l, r);
    right = Math.max(l, r);
}
```

I can achieve it by overriding `BlockQuoteSpan` ,
but just want to know is that possible to separate these by implement `getBlockQuoteMargin` for `MarkwonTheme` ,
and turn 

```
final int l = x + (dir * width);
```

into

```
final int l = x + theme.getBlockQuoteMargin();
```

maybe that would be more flexible

**Comment by noties** [comment]
Hello @gcobc12677 ,

the left margin will increase if your blockquote is nested inside some other block - this margin is the width of parent block margin. 

You also cannot control the margin from the span itself because it is handled by the TextLayout directly and is received in the `x` variable. The `dir` variable is just adjusts position in order to support RTL (right-to-left) scripts and normally is `1` or `-1`
