### ISSUE TITLE
How to implement search in tables ?

### ISSUE THREAD

**Issue by damionx7** [noties/Markwon#426]
Hey there. I can search in textview and highlight searched text. Text in table is not highlighted. How can I search in tables ?

**Comment by noties** [comment]
Hello @damionx7 ,

well, tables are implemented as a workaround, and they are pretty limited. Text is being drawn manually on canvas by the table span. So, `textView.text` would not return it, actually you would see a ` ` (space) character instead of table text contents.

Of cause you could additionally inspect the table spans and apply your styling there... but I'm not sure this is a good way to implement this
