### ISSUE TITLE
Number with dot not appearing

### ISSUE THREAD

**Issue by jemshit** [noties/Markwon#45]
Hi, i use below code to with string `1.` but TextView shows nothing:
```kotlin
 Markwon.setMarkdown(text_title, "1.")
```
Lib version: 1.0.5
Android v: 8.0.0
SDK: 27

**Comment by jemshit** [comment]
@noties hi, any due date to implement this?

**Comment by noties** [comment]
Hey @jemshit !

It looks like commonmark-java thing. A workaround would be to check if there is markdown present, for example:

```java
final String markdown = "1.";
final CharSequence cs = Markwon.markdown(this, markdown);
if (cs.length() == 0) {
    textView.setText(markdown);
} else {
    textView.setText(cs);
}
```

**Comment by jemshit** [comment]
Thanks, converted the code into extension:
```kotlin
fun TextView.setMarkdown(markdownString: String) {
    val charSequence: CharSequence = Markwon.markdown(context, markdownString)
    text = if (charSequence.isEmpty()) markdownString else charSequence
}
```

**Comment by noties** [comment]
Just a small update. The problem is not with the commonmark-java. It actually parses everything correctly. The problem is: Spans cannot have zero length (there must be at least one character in order to display a Span). In your code snippet ordered list is present, but as it has no text -  it is not shown. This problem can occur even in markdown with _more_ text. Currently there is no solution to this.
