### ISSUE TITLE
How to make link as bold

### ISSUE THREAD

**Issue by mohdaquib** [noties/Markwon#453]
* **Markwon version**: 4.6.2

1. Expected Behaviour- Make link as bold only in markdown text
2. Currently after applying bold whole markdown text is becoming bold

**Comment by ciouti** [comment]
```
**[Text](Link)**
```

**Comment by mohdaquib** [comment]
Is there any way to make it using code. I have a text from BE that doesn't have this format for links

**Comment by ciouti** [comment]
有一个比较复杂的处理方法，先用正则表达式匹配出所有的Markdown链接标签，然后找出每个匹配项的所在位置，在匹配项的起始、结束的位置分别插入两个星号，然后才进行文本渲染。

我的建议是从后往前插入星号，这样无需重新计算要插入的位置。

我的英语不是很好，所以我用了一个翻译工具，希望你能理解我发的东西。

There is a more complex approach, the first regular expression to match all the Markdown link tags, and then find the location of each match, in the match at the beginning, the end of the position were inserted two asterisks, and then text rendering.

My suggestion is to insert the asterisk from back to front so that you don't have to recalculate the position to insert.

My English is not very good, so I used a translation tool, I hope you can understand what I sent.

**Comment by mohdaquib** [comment]
I got it. Thanks. I believe this is the right approach.
