### ISSUE TITLE
Bullet lists don't work when appending to a SpannableStringBuilder

### ISSUE THREAD

**Issue by GlennNZ** [noties/Markwon#5]
I'm attempting to append multiple lines of independently processed markdown to a SpannableStringBuilder like so.

```
String line1 = "Initial _line_.";
String line2 = "List: \n* item 1 \n* item 2\n";
String line3 = "Simple _line_.";

SpannableConfiguration spannableConfiguration = SpannableConfiguration.create(this);
SpannableStringBuilder ssb = new SpannableStringBuilder();

ssb.append(Markwon.markdown(spannableConfiguration, line1));
ssb.append(Markwon.markdown(spannableConfiguration, line2));
ssb.append(Markwon.markdown(spannableConfiguration, line3));

contactTextView.setText(ssb);
```
This won't show/render the bullet points for line2. However, if the lines are appended as line2, line1 then line3 (i.e. the markdown string with the bullet points is append first, then the bullet points will render.

Is this by design or is there a bug?

**Comment by noties** [comment]
Hey!

I have looked into it and it's definitely a bug. Let me explain: there is a simple check in some of the spans, something like this:

```java
public void drawLeadingMargin(Canvas c, Paint p, int x, int dir, int top, int baseline, int bottom, CharSequence text, int start, int end, boolean first, Layout layout) {
    if (this.start != start) {
        return;
    }
}
```

`this.start` is a value that is passed by AST visitor indicating _current_ parsing position. As there are multiple parsing operations, each line will hold own indexes (starting with `0`), but when all lines are set to a TextView, TextView will pass own indexes (starting with the very first character). So, this explains why list is rendered correctly if applied first.

There is such a check in the first place in order to _not_ draw a bullet on each line if a line is too big and was split (span's `drawLeadingMargin` would be called for each such line).

Thanks for the issue, I will think of what can be done with it for the next release 👍

**Comment by noties** [comment]
@GlennNZ  It was actually an easy fix, changes are merged into develop

**Comment by GlennNZ** [comment]
We just got your develop branch going with our project and verified that all is well. Thanks for that.
