### ISSUE TITLE
Image on a newline is not parsed correctly

### ISSUE THREAD

**Issue by Adonai** [noties/Markwon#52]
With markdown like this:
```
Sample image:

<img src="https://upload.wikimedia.org/wikipedia/en/f/f4/Unrealtournament.jpg" />
```

Image is parsed as `HtmlBlock` by Commonmark parser, not as `HtmlInline`, later this is handled by `SpannableMarkdownVisitor::visit(HtmlBlock htmlBlock)` which assumes tag as `null` and passes it to `Html.fromHtml` which doesn't support images.

![image](https://user-images.githubusercontent.com/863272/43046633-72c1f11a-8dd4-11e8-8796-cac4534ed153.png)

**Comment by noties** [comment]
Hey @Adonai !

Thank you! I've created an issue in commonmark-java repository: [#133](https://github.com/atlassian/commonmark-java/issues/133)

**Comment by Adonai** [comment]
Thanks a lot!

**Comment by noties** [comment]
Hey @Adonai ! Turns out, it is not a commonmark-java bug. I will take a look and see what we can do about this issue

**Comment by Adonai** [comment]
Sure, I'll be happy to test or help in case of any struggles

**Comment by noties** [comment]
Hello @Adonai !

I've looked into the issue and found out that we might want to _redo_ current HTML implementation. Initially I thought that `HtmlBlock` and `HtmlInline` were just nodes that can contain specific HTML entities (blocks and inlines accordingly). But it turned out that for commonmark it doesn't matter what HTML entity is used as long as it is used by specific rules. What's more, `html blocks` can be interrupted by regular markdown, so simply passing an HtmlBlock content to `Html.fromHtml` won't return good results.

This all leads me to thinking of removing usage of `Html.fromHtml` at all (as it is not compliant with our usage) and writing own HTML parser/renderer... 

I'm keeping this issue open. Also, I'm going to release `1.1.0` now and then create a new branch `html` where I'm planning to do the HTML part (you are welcome to join there or express your thoughts here of cause).

**Comment by Adonai** [comment]
I won't be able to contribute much as my requirements are quite small butvwhy not, I'll take a look!

**Comment by Adonai** [comment]
Where is this branch? can't check it out

**Comment by noties** [comment]
Hey @Adonai ! I wanted to inform you that I had updated SNAPSHOT version to fix the issue that we were talking about and in general bring HTML parsing _on-site_. New version is `2.0.0`, can you please check if the issue is resolved? Plus, if new HTML parsing logic doesn't break anything... it could

Plus, on the bright side, there is a new documentation site: https://noties.github.io/Markwon/ , please tell me what do you think about it 🙌

**Comment by Adonai** [comment]
Sorry I've been in London past week.

I think dragging Jsoup into the project is an overkill, it's quite heavy and besides commonmark already contains some kind of HTML parser if I'm not mistaken. So my proposal for **default** would be - make the most obvious uses in Markdown parseable by our naive parser, make endpoints extendable and leave the heavy-lifting to the plugin (that another artifact you mentioned) where people can bring Jsoup if they feel up to it.

**Comment by Adonai** [comment]
Documentation site looks gorgeous. What did you use to make it look like this?

P.S. Will try snapshot version right now.

**Comment by Adonai** [comment]
I'll push the new snapshot to the closed alpha-tester group and play with it a week or two.

Quick update: image-on-newline case works! To be honest this bug report can be closed right away but I believe you'll be willing to let people test this extensively.

**Comment by Adonai** [comment]
Minor note:

This markdown:
```markdown
Вчера посетили самый большой кантон Швейцарии - Граубюнден. Проложили маршрут мимо озер Lag Prau Tulerigt и Caumasee к Рейнскому ущелью. [MORE=Прогуляться вместе с нами.]Озеро Lag Prau Tulerigt очень нас удивило: добравшись по карте до нужного места мы увидели огромный луг. Оказалось, что у этого озера очень колеблется уровень воды, осенью оно практически полностью высыхает, но август был безумно жаркий и без дождей, так что, видимо, оно решило высохнуть раньше.

<img alt="изображение" src="https://sun9-2.userapi.com/c831508/v831508485/17b51a/wFmqNOc1LfQ.jpg" width="80%" />

 Небольшое количество воды в озере все-таки обнаружено!
```

looks like this: 

![image](https://user-images.githubusercontent.com/863272/44432469-d1578f80-a5aa-11e8-92a5-4540c9140013.png)

i.e. the image is on a new paragraph but the text following it is not, just a line break.

**Comment by noties** [comment]
Hey @Adonai !

About **Jsoup**. It turned out that it's not that heavy. And if you strip all _unused_ code that does selectors and fixing malicious HTML content, it's about ~100KB. I think for the control that we get over HTML it bearable. Anyway, Jsoup (like TagSoup) cannot be used by Markwon directly as they do not allow processing HTML input in chunks. I had to repackage Jsoup parsing (Tokeniser) functionality and introduce some minor changes. There is still ability to **not** include HTML parser (it is in different artifact). And there is of cause an ability to provide own implementation (API is defined in `markwon-html-parser-api` artifact, you can inspect it, and maybe create something that will answer your needs).

About **documentation**. I used [vuepress](https://vuepress.vuejs.org/). It's absolutely amazing. At least compared with Jekyll. It's perfect for technical documentation (not so good for blogging though). I think it's the engine behind all Vue.js documentation (pretty cool also).

About markdown **fragment** that you provided. I just used [commonmark-dingus](https://spec.commonmark.org/dingus/?text=%23%23%20Try%20CommonMark%0A%0A%D0%92%D1%87%D0%B5%D1%80%D0%B0%20%D0%BF%D0%BE%D1%81%D0%B5%D1%82%D0%B8%D0%BB%D0%B8%20%D1%81%D0%B0%D0%BC%D1%8B%D0%B9%20%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%BE%D0%B9%20%D0%BA%D0%B0%D0%BD%D1%82%D0%BE%D0%BD%20%D0%A8%D0%B2%D0%B5%D0%B9%D1%86%D0%B0%D1%80%D0%B8%D0%B8%20-%20%D0%93%D1%80%D0%B0%D1%83%D0%B1%D1%8E%D0%BD%D0%B4%D0%B5%D0%BD.%20%D0%9F%D1%80%D0%BE%D0%BB%D0%BE%D0%B6%D0%B8%D0%BB%D0%B8%20%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%20%D0%BC%D0%B8%D0%BC%D0%BE%20%D0%BE%D0%B7%D0%B5%D1%80%20Lag%20Prau%20Tulerigt%20%D0%B8%20Caumasee%20%D0%BA%20%D0%A0%D0%B5%D0%B9%D0%BD%D1%81%D0%BA%D0%BE%D0%BC%D1%83%20%D1%83%D1%89%D0%B5%D0%BB%D1%8C%D1%8E.%20%5BMORE%3D%D0%9F%D1%80%D0%BE%D0%B3%D1%83%D0%BB%D1%8F%D1%82%D1%8C%D1%81%D1%8F%20%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B5%20%D1%81%20%D0%BD%D0%B0%D0%BC%D0%B8.%5D%D0%9E%D0%B7%D0%B5%D1%80%D0%BE%20Lag%20Prau%20Tulerigt%20%D0%BE%D1%87%D0%B5%D0%BD%D1%8C%20%D0%BD%D0%B0%D1%81%20%D1%83%D0%B4%D0%B8%D0%B2%D0%B8%D0%BB%D0%BE%3A%20%D0%B4%D0%BE%D0%B1%D1%80%D0%B0%D0%B2%D1%88%D0%B8%D1%81%D1%8C%20%D0%BF%D0%BE%20%D0%BA%D0%B0%D1%80%D1%82%D0%B5%20%D0%B4%D0%BE%20%D0%BD%D1%83%D0%B6%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BC%D0%B5%D1%81%D1%82%D0%B0%20%D0%BC%D1%8B%20%D1%83%D0%B2%D0%B8%D0%B4%D0%B5%D0%BB%D0%B8%20%D0%BE%D0%B3%D1%80%D0%BE%D0%BC%D0%BD%D1%8B%D0%B9%20%D0%BB%D1%83%D0%B3.%20%D0%9E%D0%BA%D0%B0%D0%B7%D0%B0%D0%BB%D0%BE%D1%81%D1%8C%2C%20%D1%87%D1%82%D0%BE%20%D1%83%20%D1%8D%D1%82%D0%BE%D0%B3%D0%BE%20%D0%BE%D0%B7%D0%B5%D1%80%D0%B0%20%D0%BE%D1%87%D0%B5%D0%BD%D1%8C%20%D0%BA%D0%BE%D0%BB%D0%B5%D0%B1%D0%BB%D0%B5%D1%82%D1%81%D1%8F%20%D1%83%D1%80%D0%BE%D0%B2%D0%B5%D0%BD%D1%8C%20%D0%B2%D0%BE%D0%B4%D1%8B%2C%20%D0%BE%D1%81%D0%B5%D0%BD%D1%8C%D1%8E%20%D0%BE%D0%BD%D0%BE%20%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%20%D0%BF%D0%BE%D0%BB%D0%BD%D0%BE%D1%81%D1%82%D1%8C%D1%8E%20%D0%B2%D1%8B%D1%81%D1%8B%D1%85%D0%B0%D0%B5%D1%82%2C%20%D0%BD%D0%BE%20%D0%B0%D0%B2%D0%B3%D1%83%D1%81%D1%82%20%D0%B1%D1%8B%D0%BB%20%D0%B1%D0%B5%D0%B7%D1%83%D0%BC%D0%BD%D0%BE%20%D0%B6%D0%B0%D1%80%D0%BA%D0%B8%D0%B9%20%D0%B8%20%D0%B1%D0%B5%D0%B7%20%D0%B4%D0%BE%D0%B6%D0%B4%D0%B5%D0%B9%2C%20%D1%82%D0%B0%D0%BA%20%D1%87%D1%82%D0%BE%2C%20%D0%B2%D0%B8%D0%B4%D0%B8%D0%BC%D0%BE%2C%20%D0%BE%D0%BD%D0%BE%20%D1%80%D0%B5%D1%88%D0%B8%D0%BB%D0%BE%20%D0%B2%D1%8B%D1%81%D0%BE%D1%85%D0%BD%D1%83%D1%82%D1%8C%20%D1%80%D0%B0%D0%BD%D1%8C%D1%88%D0%B5.%0A%0A%3Cimg%20alt%3D%22%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5%22%20src%3D%22https%3A%2F%2Fsun9-2.userapi.com%2Fc831508%2Fv831508485%2F17b51a%2FwFmqNOc1LfQ.jpg%22%20width%3D%2280%25%22%20%2F%3E%0A%0A%D0%9D%D0%B5%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%BE%D0%B5%20%D0%BA%D0%BE%D0%BB%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%BE%20%D0%B2%D0%BE%D0%B4%D1%8B%20%D0%B2%20%D0%BE%D0%B7%D0%B5%D1%80%D0%B5%20%D0%B2%D1%81%D0%B5-%D1%82%D0%B0%D0%BA%D0%B8%20%D0%BE%D0%B1%D0%BD%D0%B0%D1%80%D1%83%D0%B6%D0%B5%D0%BD%D0%BE!%0A%0A) and it renders it the same. Adding a `<br>` makes text after image to be in a different paragraph.
