### ISSUE TITLE
Image scale preserving aspect ratio with Spannable logic

### ISSUE THREAD

**Issue by CraggyHaggy** [noties/Markwon#64]
Hello, thanks for the library. I have a question about image size.
According to default `ImageSizeResolverDef` implementation for `Spannable` case, my image is cut off. I want my image to be scaled preserving aspect ratio. Is it possible to implement?

This is cut image:
![cut_image](https://user-images.githubusercontent.com/13361984/45061249-53b47900-b0ac-11e8-883b-21919be42207.png)

This is full image:
<img width="1026" alt="full_image" src="https://user-images.githubusercontent.com/13361984/45061251-53b47900-b0ac-11e8-898c-c15d98dae1d6.png">

**Comment by noties** [comment]
Hello @CraggyHaggy ,

It definitely should be as you mention, image should be scaled to fit width of a TextView (whilst keeping the ratio). Unfortunately this piece of logic was mistakenly excluded from previous releases. But the good thing is I have identified and fixed it in SNAPSHOT version. Can you please check with it? `2.0.0-SNAPSHOT` (information of how to add it to your project is in the README)

Also, I want to notice, that you can use HTML `<img>` tag and specify `width` attribute (it accepts percent units):

```html
<img src="my-image.JPEG" width="100%" />
```

But in current stable release it also might not work as expected (see #52 for reference). But, again, it is fixed in SNAPSHOT version, which will be released soon (at least I hope so).

There is also an option of implementing own `ImageSizeResolver` which can handle all logic that you might have (see [documentation](https://noties.github.io/Markwon/docs/configure.html#size-resolver) for more info)

**Comment by CraggyHaggy** [comment]
I will try this logic in `SNAPSHOT` version. Thandk for the advice.

**Comment by noties** [comment]
np 👍
