### ISSUE TITLE
Feature request: Parser adapter and renderer adapter

### ISSUE THREAD

**Issue by IlyaGulya** [noties/Markwon#69]
Hello!
Looks like currently library supports only commonmark-java for parsing Markdown.
Here is a lot more powerful library named [flexmark-java](https://github.com/vsch/flexmark-java).
It supports more markdown dialects and extensions.

How about adding ability to make some kind of adapter interface for parser to be able to use libraries other than commonmark-java?

I think to make it possible we need:

- Make parser adapter
- Make renderer adapter

**Comment by noties** [comment]
Hello @IlyaGulya !

I'm aware of flemark-java. It's definitely more feature-full than commonmark-java (flexmark-java is also a fork of commonmark-java). But I do not think that creating 2 adapters will help to achieve multiple parsers support. Of cause, the idea is great, but I do not see a way currently. It's more like switch to flexmark-java than add support to it (due to various differences between the two). 

There are also things to consider:
* commonmark-java has better performance
* with #65 each plugin will have to define implementation for each parser
* there is an open [issue](https://github.com/atlassian/commonmark-java/issues/113) in commonmark-java repository that can make things a tad better (extensible inline parser) after it is resolved (although it's open for some time..)

But anyway if you see how this can be done with minimal damage, you are absolutely welcome to share it, it would be a great feature 100% 🙌
