### ISSUE TITLE
Problem rendering Links if link does not start with 'http'

### ISSUE THREAD

**Issue by tariqueislam** [noties/Markwon#75]
This works as expected:
```[I'm an inline-style link](https://www.google.com)```

These are unresponsive to click:  
```
[I'm an inline-style link](www.google.com)  
[I'm an inline-style link](google.com)
```
I have tested on markwon v2.0.0

**Comment by noties** [comment]
Hello @tariqueislam !

Yeah, I think this is because `LinkResolverDef` cannot find an Activity to open such an URL. If you look in the logcat output _most likely_ you will see `Actvity was not found for intent, ...`. So you can create own `LinkSpan.Resolver` and check if supplied URL has scheme info and add it to resulting destination.

**Comment by tariqueislam** [comment]
Thanks for the helpful info @noties . I ended up using my own ```LinkSpan.Resolver``` with an additional check:
```
if (uri.getScheme() == null) {
    uri = Uri.parse("http://" + link);
}
```

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
Hi @noties ,
first of all: Thank you for your amazing library!

I am having the exact same problem as described in this issue (including `Actvity was not found for intent` in my logs), but I see there is no `LinkSpan.Resolver` class.
I am using **Markwon 4.2.0** (latest stable release at this time, as far as I am aware).

I have been able to fix this by writing a custom plugin like so:
```java
final Markwon markwon = Markwon.builder(this)
                        .usePlugin(new AbstractMarkwonPlugin() {
                            @Override
                            public void configureConfiguration(@NonNull MarkwonConfiguration.Builder builder) {
                                // own instance of resolver, will be called for all links in your markdown
                                builder.urlProcessor(new UrlProcessor() {
                                    @NonNull
                                    @Override
                                    public String process(@NonNull String destination) {
                                        return !destination.startsWith("http://") && !destination.startsWith("https://") ? "http://"+destination : destination;
                                    }
                                });
                            }
                        }).build();
```
It works! However, @noties perhaps you could make the default behaviour of Markwon to do this if url's without appearently neccessary http(s) prefix?

It would have saved me 2 hours of head-scratching, and probably will auto-magically fix this problem for all people in the future.

**Comment by noties** [comment]
Hello @Sebastiaan-Alvarez-Rodriguez !

`LinkSpan.Resolver` was changed in `4.0.0` version to become `LinkResolver` and `CHANGELOG.md` fails to indicate it more clearly. I will update it.

Anyway, I agree with you that a link without scheme doesn't make sense and `Markwon` can safely _assume_ that if it's missing - `https` can be used instead. I think it would cover most of the use cases (URL to a web page). 

But `UrlProcessor` is not a good place to do so because it processes all the URLs in a markdown document (links and images). What's more, now I think about it and see that its primary target is actually images. For example, `UrlProcessorAndroidAssets` treats all URLs without a scheme to point to the `assets` folder. It works for images, but in case of a link - `file:///android_asset/www.my.site` would make very little sense. Another bundled `UrlProcessor` is the `UrlProcessorRelativeToAbsolute`, which is instantiated with the _base_ URL and then resolves all relative links, so `../index.html` would become `https://hel.lo/index.html` when created with `https://hel.lo/base/` as the base. It might appear useful in general but I don't think it is a very frequently used feature of the library. And the only usage that I'm aware of is the `UrlProcessorInitialReadme` which downloads images from the Github (only for the `Markwon` repository) 😄 .

So, I'm thinking of adding `https` as default fall-back scheme if it's missing in the `LinkResolverDef` in the next `4.3.0` version, meanwhile deciding the future of the `UrlProcessor` (most likely rename).

Thanks for bringing it up @Sebastiaan-Alvarez-Rodriguez 🙌

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
Hi,
thanks for your response!
For now, I will try to use the 'LinkResolver'! Once 4.3.0 stable is out, I will check implementation of fallback schemes and remove the code.

Anyway, thanks again for your time!
