### ISSUE TITLE
Fail to interpret bold style

### ISSUE THREAD

**Issue by DSofter** [noties/Markwon#88]
Hello again!

I found another small issue, where the bold style doesn't show up correctly. Do you mind taking a look?

Markdown:
```
**Tools Used:**In creating my work, I mainly used Adobe Illustrator CC 2019 for making the
```

Outcome:
![image](https://user-images.githubusercontent.com/1687829/50065692-ace07e00-016c-11e9-9f9d-7989d8c9374f.png)

**Comment by noties** [comment]
Hey @DSofter !

I tried your input in [dingus](https://spec.commonmark.org/dingus/?text=**Tools%20Used%3A**In%20creating%20my%20work%2C%20I%20mainly%20used%20Adobe%20Illustrator%20CC%202019%20for%20making%20the%0A%0A) and got interesting results. If we remove `:` -> everything will be rendered correctly. I experimented and it turns out that any **non** alphanumeric symbol will break this. Of cause if you add a space between `**` and `In creating...` bold will also be present. I'm not sure why, but I guess somewhere deep in the commonmark specification this thing is described. Because `commonmark-java` follows specification pretty closely (runs against the whole specification test suite). At this point I'm not sure if it's a bug or a feature... But here we are

**Comment by noties** [comment]
Hey @DSofter !

Glad I could help. I would love to accept your donation as long as I get to use your app 😉 . Should I drop a line to an email that you had mentioned in #78?

**Comment by DSofter** [comment]
@noties Do you want to email me at dsofterwolf@gmail.com? Thanks!
