### ISSUE TITLE
Table HTML tag support

### ISSUE THREAD

**Issue by DSofter** [noties/Markwon#89]
Hey! I'm back with another question!

I try the following text in dingus and it worked well:
```
<table>
<tr>
<td>row1 col1</td>
<td>row1 col2</td>
</tr>
<tr>
<td>row2 col1</td>
<td>row2 col2</td>
</tr>
</table>
```

![image](https://user-images.githubusercontent.com/1687829/50405810-051c0f00-076f-11e9-908f-ff6d8f83c455.png)

However when i tried Markwon it seems to be ignoring the format:
![image](https://user-images.githubusercontent.com/1687829/50405817-1f55ed00-076f-11e9-8333-1ded78d786f3.png)
![image](https://user-images.githubusercontent.com/1687829/50405818-23820a80-076f-11e9-876c-008581f8c83d.png)

Its there anything I was missing?

Merry Christmas!

**Comment by noties** [comment]
Hey @DSofter !

Dingus is a great tool to evaluate markdown and compare expected/actual results. But it's web-based. If it sees HTML (which is valid markdown) it will render it. As it's run in a web-browser there is no problem for dingus to do so. We, on the other hand, operate in a different environment. Markwon supports small subset of HTML, but not all. In order to properly handle tables we must define our own tag handler(s). Good news it's completely possible. Bad news that it will require big amount of work. For a reference you can see how currently supported HTML tags are handled in `ru.noties.markwon.renderer.html2.tag` package.

Why won't you use markdown tables in this case?

Merry Christmas!

**Comment by noties** [comment]
I'm closing this now, but feel free to open it again in order to proceed with discussion
